---
- name: Adding aliases to {{ zookeeper.hosts_file }}
  lineinfile:
    path: "{{ zookeeper.hosts_file }}"
    create: true
    line: "{{ hostvars[item].private_ip }} {{ hostvars[item].alias }}"
  with_items: "{{ groups['zookeeper_hosts'] }}"

- name: "Creates and change permissons to data and log directories."
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0777"
  with_items:
    - "{{ zookeeper.home }}"
    - "{{ zookeeper.data_dir }}"
    - "{{ zookeeper.log_dir }}"

- name: Download zookeeper
  get_url:
    url: http://archive.apache.org/dist/zookeeper/zookeeper-{{ zookeeper.version }}/apache-zookeeper-{{ zookeeper.version }}-bin.tar.gz
    dest: "{{ zookeeper.home }}"

- name: Extract Zookeeper dist
  unarchive:
    remote_src: yes
    src: "{{ zookeeper.home }}/apache-zookeeper-{{ zookeeper.version }}-bin.tar.gz"
    dest: "{{ zookeeper.home }}"
    extra_opts: [--strip-components=1]

- name: Delete tar dist
  file:
    path: "{{ zookeeper.home }}/apache-zookeeper-{{ zookeeper.version }}-bin.tar.gz"
    state: absent

- name: Creating myid file in {{ zookeeper.data_dir }}.
  template: src=myid.j2 dest={{ zookeeper.data_dir }}/myid
  tags: deploy

- name: Creating zookeeper config file - {{ zookeeper.home }}/conf/{{ zookeeper.config_file }}
  template: src=zoo.cfg.j2 dest={{ zookeeper.home }}/conf/{{ zookeeper.config_file }}
  tags: deploy

- include: daemon_service.yml
  when: zookeeper.daemon.type == 'service'
- include: daemon_systemctl.yml
  when: zookeeper.daemon.type == 'systemctl'
